name: Deploy Hugo site to OVH

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. Installer Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.125.0"
          extended: true

      # 2.1 Installer Go (Hugo Modules en ont besoin)
      - name: Setup Go (required for Hugo Modules)
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # 3. Build du site
      - name: Build site
        run: hugo --minify

      # 4. Déploiement FTP vers OVH
      - name: Deploy to OVH FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: /blog/
          dangerous-clean-slate: true